name: Take last changed files
run-name: ${{ github.workflow }} by @${{ github.actor }}

on:
  push:

jobs:
  TerraformFMT:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
        - uses: actions/checkout@v3
        - name: Reformat YAML Files
          uses: credfeto/action-yaml-format@v1.3.2
        - name: Add a random file
          id: randomfile
          run: ls -la > lsla-$(date +%Y%m%d%H%M).txt
        - name: Place pwd
          id: pwd
          run: pwd > pwd-$(date +%Y%m%d%H%M).txt
        - name: Pick changed files
          id: changed
          uses: hellofresh/action-changed-files@v3
        - name: Check values
          id: cheking
          run: echo ${{ steps.changed.outputs.matrix }}
        - name: Git Status
          id: gitstatus
          run: git status
        

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v5.0.2
          with:
          
            commit-message: Cloud - Update terraform format
            title: Cloud - Update terraform format
            body: Cloud - Update terraform format ${{ steps.changed.outputs.matrix }}
            base: master
            labels: automated-pr, terraform
            branch: hotfix/terraform-update-format

            
            delete-branch: true
