name: Take last changed files
on:
  push:

jobs:
  TerraformFMT:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
        - uses: actions/checkout@v3
        - name: Reformat YAML Files
          uses: credfeto/action-yaml-format@v1.3.2

        - name: Pick changed files
          id: changed
          uses: hellofresh/action-changed-files@v3

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            commit-message: Cloud - Update terraform format
            title: Cloud - Update terraform format
            body: Cloud - Update terraform format ${{ steps.changed.outputs.matrix }}
            base: master
            labels: automated-pr, terraform
            branch: hotfix/terraform-update-format
            delete-branch: true
